### ISSUE TITLE
Uncaught TypeError: this.material.updateUniformsAndDefines is not a function

### ISSUE THREAD

**Issue by ahmadasaad89** [lumalabs/luma-web-examples#10]
I am getting this error when trying to use Luma splats with React Three Fiber

```
luma-web.module.js:60 Uncaught TypeError: this.material.updateUniformsAndDefines is not a function
    at a.onBeforeRender (luma-web.module.js:60:354411)
    at renderObject (three.module.js:29444:1)
    at renderObjects (three.module.js:29434:1)
    at renderScene (three.module.js:29303:1)
    at WebGLRenderer.render (three.module.js:29121:1)
```

I am following the example you have exactly [here](https://github.com/lumalabs/luma-web-examples?tab=readme-ov-file#react-three-fiber) 

Any idea what might be causing this error?

**Comment by haxiomic** [comment]
Hi @ahmadasaad89, could you delete node_modules, make a zip of your project and upload here? I will see if I can spot the error

**Comment by haxiomic** [comment]
Hi @ahmadasaad89, could you delete node_modules, make a zip of your project and upload here? I will see if I can spot the error
